version: "3.8"

services:
  # Development service
  dev:
    build:
      context: .
      target: builder
    image: gateway-mgmt-tool-demo:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: yarn dev --host 0.0.0.0
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Production service
  prod:
    build: .
    image: gateway-mgmt-tool-demo:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # Test service
  test:
    image: cypress/included:14.2.0
    volumes:
      - .:/e2e
    working_dir: /e2e
    environment:
      - NODE_ENV=test
      - CYPRESS_baseUrl=http://localhost:5173
      - CYPRESS_video=false
    depends_on:
      - dev
    network_mode: "host"

networks:
  app-network:
    name: gateway-mgmt-network
    driver: bridge
