name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # Add more Node.js versions if needed

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint & Format
        run: yarn lint && yarn format

      - name: Build
        run: yarn build

      - name: Start dev server
        run: |
          yarn dev &
          sleep 10 # Wait for server to start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: false # Set to true if you have Cypress Dashboard
          wait-on: "http://localhost:5173"
          config-file: cypress.config.ts
        env:
          CYPRESS_baseUrl: http://localhost:5173

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-videos
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7
